language: cpp

env:
  - EVAL="CXX=g++-6"
  - EVAL="CXX=clang++-3.8"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
      - sourceline: 'deb http://ppa.launchpad.net/openmw/openmw/ubuntu trusty main'
    packages:
      - clang-3.8
      - g++-6
      - cmake
      - zlib1g-dev
      - libbullet-dev
      - libopenscenegraph-dev

before_install:
  - eval "${EVAL}"

script:
- mkdir build
- cd build
- cmake ..
- make -j 2
